//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BINHLUAN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string ID_BL { get; set; }
        public string ID_TK { get; set; }
        public string ID_DD { get; set; }
        public string NOIDUNG_BL { get; set; }
        public Nullable<int> LUOTTHICH_BL { get; set; }
        public Nullable<System.DateTime> NGAY_BL { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
