//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEMYEUTHICH
    {
        public string ID_DDYT { get; set; }
        public string ID_TK { get; set; }
        public string ID_DD { get; set; }
        public System.DateTime NgayThich { get; set; }
    }
}
