//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIADIEM()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.HINHANHs = new HashSet<HINHANH>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string ID_DD { get; set; }
        public string ID_TK { get; set; }
        public int ID_LOAIDD { get; set; }
        public int ID_PX { get; set; }
        public string TEN_DD { get; set; }
        public string TOADO_DD { get; set; }
        public string MOTA_DD { get; set; }
        public Nullable<int> LUOTTHICH_DD { get; set; }
        public Nullable<System.DateTime> NGAYTHEM_DD { get; set; }
        public Nullable<bool> LADIEMCANHAN { get; set; }
        public string DIACHI_DD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual LOAIDIADIEM LOAIDIADIEM { get; set; }
        public virtual PHUONGXA PHUONGXA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
