//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public string ID_HA { get; set; }
        public string ID_DD { get; set; }
        public string ID_TK { get; set; }
        public string LINK_HA { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
