//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.DIADIEMs = new HashSet<DIADIEM>();
            this.HINHANHs = new HashSet<HINHANH>();
            this.BINHLUANs1 = new HashSet<BINHLUAN>();
            this.DIADIEMs1 = new HashSet<DIADIEM>();
        }
    
        public string ID_TK { get; set; }
        public int ID_LOAITK { get; set; }
        public string TAIKHOAN_TK { get; set; }
        public string MATKHAU_TK { get; set; }
        public string EMAIL_TK { get; set; }
        public string SDT_TK { get; set; }
        public string TENHIENTHI_TK { get; set; }
        public Nullable<System.DateTime> NGAYTAO_TK { get; set; }
        public Nullable<System.DateTime> LANHDCUOI_TK { get; set; }
        public Nullable<bool> DAKHOA_TK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIADIEM> DIADIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        public virtual LOAITAIKHOAN LOAITAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIADIEM> DIADIEMs1 { get; set; }
    }
}
